app.base-url: http://localhost:8080/
# ===============================
# DB CONNECTION
# ===============================
spring.datasource.url: jdbc:mysql://127.0.0.1:3306/link-shorter?useUnicode=true&serverTimezone=Europe/Moscow
spring.datasource.username: root
spring.datasource.password: "kBcjCg872rbxuCnAZF3w+ZZtHH[87qzudZc/"
# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.show-sql: true
spring.jpa.hibernate.ddl-auto: update
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
spring.jpa.properties.hibernate.enable_lazy_load_no_trans: true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false